export enum EConfiguration {
  PORT = 'PORT',
  SCHEDULE = 'SCHEDULE',
  ACTIVE = 'ACTIVE',
  BASE_URL = 'BASE_URL',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  TIMEOUT = 'TIMEOUT',
  USER_ID = 'USER_ID',
  CRYPTO_ALGORITHM = 'CRYPTO_ALGORITHM',
  CRYPTO_IV = 'CRYPTO_IV',
  CRYPTO_PASSWORD = 'CRYPTO_PASSWORD'
}