export enum EAction {
  CLICK = 'CLICK',
  TYPE = 'TYPE',
  INNER_TEXT = 'INNER_TEXT',
  TAKE_SCREENSHOT = 'TAKE_SCREENSHOT',
  VALIDATE = 'VALIDATE',
  COOKIES = 'COOKIES',
  REQUEST = 'REQUEST',
  NAVIGATE = 'NAVIGATE',
  XPATH = 'XPATH',
  EVALUATE = 'EVALUATE',
  NOTIFY = 'NOTIFY',
}